"""Remove unique constraint from username

Revision ID: 407dc0f239e6
Revises: 2c926b23428f
Create Date: 2025-08-10 19:58:32.856243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '407dc0f239e6'
down_revision = '2c926b23428f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('username'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('username'), ['username'], unique=True)

    # ### end Alembic commands ###
