"""Made date consistent everywhere

Revision ID: 44c774dcfe51
Revises: 9e676ff9ed35
Create Date: 2025-08-17 11:47:16.115181

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44c774dcfe51'
down_revision = '9e676ff9ed35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
        batch_op.alter_column('updated_at',
               existing_type=mysql.DATETIME(),
               type_=sa.Date(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))
        batch_op.alter_column('created_at',
               existing_type=sa.Date(),
               type_=mysql.DATETIME(),
               existing_nullable=True,
               existing_server_default=sa.text('(now())'))

    # ### end Alembic commands ###
