"""add indexes and relationships to all models

Revision ID: 799e42e1539a
Revises: 73a3204a6cb1
Create Date: 2026-04-30 23:43:19.465142

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '799e42e1539a'
down_revision = '73a3204a6cb1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.create_index('ix_budget_categories_budget_id', ['budget_id'], unique=False)

    with op.batch_alter_table('budget_expenses', schema=None) as batch_op:
        batch_op.create_index('ix_budget_expenses_budget_id_category_id', ['budget_id', 'budget_category_id'], unique=False)
        batch_op.create_index('ix_budget_expenses_user_id_date', ['user_id', 'date'], unique=False)

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.create_index('ix_budgets_user_id_start_end', ['user_id', 'start_date', 'end_date'], unique=False)

    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index('ix_expenses_user_id_date', ['user_id', 'date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_expenses_user_id_date')

    with op.batch_alter_table('budgets', schema=None) as batch_op:
        batch_op.drop_index('ix_budgets_user_id_start_end')

    with op.batch_alter_table('budget_expenses', schema=None) as batch_op:
        batch_op.drop_index('ix_budget_expenses_user_id_date')
        batch_op.drop_index('ix_budget_expenses_budget_id_category_id')

    with op.batch_alter_table('budget_categories', schema=None) as batch_op:
        batch_op.drop_index('ix_budget_categories_budget_id')

    # ### end Alembic commands ###
