"""Doing some small changes

Revision ID: 9e676ff9ed35
Revises: c1e1b6e5bb11
Create Date: 2025-08-17 11:45:23.239361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e676ff9ed35'
down_revision = 'c1e1b6e5bb11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_expenses_budget_id'), ['budget_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_expenses_budget_id'))

    # ### end Alembic commands ###
